import mongoose from 'mongoose'
import cloudinary from 'cloudinary'
import { Request, Response, NextFunction } from 'express'
import asyncHandler from '../middleware/async-handler'
import ErrorHandler from '../utils/error-handler'
import { redis } from '../config/redis'
import OrderModel, { IOrder } from '../models/order-model'
import UserModel from '../models/user-model'
import CourseModel from '../models/course-model'
